### ISSUE TITLE
JSONフォーマットのご相談

### ISSUE THREAD

**Issue by AkiyukiOkayasu** [yasuhito/qni-viewer#51]
## JSONフォーマットの希望例

```JSON
{
	"circuit": [
		[
			{
				"gate": "H"
			},
			{
				"gate": "X"
			},
			{
				"gate": "Phase",
				"angle": 3.14
			}
		],
		[
			null,
			null,
			null
		],

		[
			null,
			{
				"gate": "Phase",
				"angle": -3.14
			},
			{
				"gate": "Y"
			}
		]
	],
	"step": 0
}
```

## angleフィールド付きのゲート

Phase, RX, RY, RZはangleのフィールドも必要。角度はラジアンで数値型で指定。

```JSON
{
        "gate": "Phase",
        "angle": 3.14
}
```

## 空きゲート/ステップ

現行フォーマットで"1"で表現している空きゲートはnullで表現する。  
あるステップ全て空きステップの場合は要素数ゼロの配列でも表現できる。したがって以下の2ステップは実質的には同じ。

```JSON
{
	"circuit": [
		[
			null,
			null,
			null
		],
		[]
	],
	"step": 0
}
```

以上何卒よろしくお願いいたします。

**Comment by yasuhito** [comment]
@AkiyukiOkayasu JSON フォーマットの変更ですが、変更点は最低限で以下のようにするのはいかがでしょうか。

- Phase ゲートについては、`"P(π/2)"` ではなく `"P(1.5707963267948966)"` と即値を入れてしまう
- 空のステップは `[]` で

先ほど「できそう」とお返事してしまったのですが、実装してみたところブラウザでの回路表示ができなくなってしまうことが分かりました。すみません。

![CleanShot 2024-10-21 at 15 37 12](https://github.com/user-attachments/assets/826959d0-2e26-47dd-8a33-01725da03329)


これは、回路を表示する `<quantum-circuit>` コンポーネントに Qni JSON フォーマットを渡す必要があり、フォーマットを変えてしまうと動作しなくなるためです。

```html
<!-- data-json に Qni 形式の JSON を入れる -->
<quantum-circuit data-json="...">
</quantum-circuit>
```

ご提案した変更は Qni の JSON フォーマットに準じているため、正しく動作します。

**Comment by AkiyukiOkayasu** [comment]
@yasuhito 承知しました、この方針でお願いします。

> - Phase ゲートについては、"P(π/2)" ではなく "P(1.5707963267948966)" と即値を入れてしまう
> - 空のステップは [] で

**Comment by AkiyukiOkayasu** [comment]
## circuit_jsonの型の件

すみません、打ち合わせで自分がぼんやりした返答をしてしまったせいで行き違いが起きてる気がしておりまして...。下記のcircuit_jsonフィールドが文字列型なのが気になるということを言いたかったです。

https://github.com/yasuhito/qni-viewer/blob/380e48e22a7e69172545ed2a53e641c0dbaddd7a/README.md?plain=1#L79-L86

こうしたオブジェクトでいいのではないかと思うのですが、いかがでしょうか。
```json
{
    "circuit_json": {
        "cols": [
            ["|0>"],
            ["H"],
            ["Measure"]
        ]
    },
    "step": 1
}
```

### cURLの実行例

現仕様の送信例はこちらですが、

https://github.com/yasuhito/qni-viewer/blob/380e48e22a7e69172545ed2a53e641c0dbaddd7a/README.md?plain=1#L96-L106

オブジェクトならこのように送信できるのでは？ということをお伝えするつもりでした。

```sh
curl -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -d '{
        "circuit_json": {
            "cols": [
                ["|0>"],
                ["H"],
                ["Measure"]
            ]
        },
        "step": 1
    }' \
    -XGET http://localhost:3000/
```

何らかの都合があって文字列として扱っているのかもですが、もし大したお手間でなければオブジェクトとして扱えないでしょうか？
といいますのもオブジェクトの方が私のシリアライザの実装が楽だからなのですが...、ご検討いただけますと幸いです。
普段API叩いたりといったことはあまりしないもので、もし頓珍漢なことを言っていたらすみません。

**Comment by yasuhito** [comment]
@AkiyukiOkayasu ご説明ありがとうございます。JSON オブジェクトそのままでも渡せるように改良します。
`<quantum-circuit>` の `data-json` で文字列を渡すので、なんとなく JSON はすべて文字列と仮定してしまっていました。
こちら修正できましたらまたご連絡します。

**Comment by AkiyukiOkayasu** [comment]
ありがとうございます！

**Comment by yasuhito** [comment]
@AkiyukiOkayasu #57 で対応しましたので、ご確認おねがいします!

**Comment by AkiyukiOkayasu** [comment]
取り急ぎcURLでJSONオブジェクトに対応していただいたのを確認しました。大変助かりました、ありがとうございます！

私としては、フォーマットに関することはもう完璧だと思いますのでcloseしていただいて構いません。

**Comment by AkiyukiOkayasu** [comment]
ちょっと早まりました、方針は決まってますが、まだ[]の空配列のご対応とか色々ありましたね。すみません。

**Comment by yasuhito** [comment]
いえ! とりあえず JSON フォーマット自体は定まったと思うので、[] の表示とかは別イシューにすることにして、こちらはいったん閉じます。
