### ISSUE TITLE
回路フォーマットの固定

### ISSUE THREAD

**Issue by yasuhito** [yasuhito/qni-viewer#53]
@AkiyukiOkayasu ご相談です。以下の仕様ですが、送る側から毎回このように送ってもらうことは可能でしょうか

1. 量子ビット数: 3qubit 固定
2. ステップ数: 17 ステップ固定
3. 最初のステップはすべて 0、最後にすべて測定

つまり送っていただく JSON としては、以下のようになります。

```
{"cols":[["|0>","|0>","|0>"],["H"],["•","X"],[],[],[],[],[],[],[],[],[],[],[],[],[],["Measure","Measure","Measure"]]}
```

というのももし Qni viewer 側でこれらを固定しまうと、(たぶんそんなことは起こらないと思いますが) もしステップ数や量子ビット数が変更になった場合、送信側と Qni viewer 側両方の変更が必要になってくるためです。なので、送る側で明示的に指定していただければ Qni viewer 側はそのまま計算 & 表示するだけで良くなります。

ご検討のほどよろしくおねがいします。

**Comment by AkiyukiOkayasu** [comment]
ありがとうございます、承知しました。

最初の["|0>","|0>","|0>"]や最後の["Measure","Measure","Measure"]を毎回つけるのも全く手間ではありませんので、もしやっぱりこちら側で送った方がよさそうだとかあればいつでもご相談ください。

**Comment by yasuhito** [comment]
了解です!
