### ISSUE TITLE
空のステップを詰めずに表示

### ISSUE THREAD

**Issue by yasuhito** [yasuhito/qni-viewer#55]
回路 JSON に以下のように空のステップがあった場合に、回路表示で空ステップを詰めず空白を開けて表示する。

```json
{"cols":[["|0>","|0>"],[],["H"],[], [], ["•","X"],["Measure"],[1,"Measure"]]}
```

おそらく `<quantum-circuit>` コンポーネントに `data-allow-empty-steps` みたいなオプションを付ける?

**Comment by yasuhito** [comment]
![CleanShot 2024-11-01 at 10 45 25](https://github.com/user-attachments/assets/7a57624f-bd8d-4d46-8c36-da4f9b305b90)

@AkiyukiOkayasu 空のステップ `[]` およびオラクル `["Oracle3"]` ですが、Qni の回路コンポーネントの変更がまだなので、一時的に次のように代替表示するようにしました。

- 空ステップは "…" 3 つで表現
- オラクルはブロッホ球 3 つで表現

これでひとまず必要なゲートはそろったと思います。ご確認よろしくおねがいします。

**Comment by AkiyukiOkayasu** [comment]
@yasuhito Oracle3と空のステップの動作確認できました。全く問題なく動作しているかと思います。ご対応ありがとうございます。

**Comment by AkiyukiOkayasu** [comment]
@yasuhito 何度も通知飛ばしてすみません。
以下のcURLコマンドで全て空ステップに指定するとスクショのエラーが返ってきました。こんな無意味なリクエスト投げる方がおかしいとは思いますが...。

```shell
curl -X GET http://localhost:3000/ -H 'accept: application/json' -H 'content-type: application/json' -H 'content-type: application/json' -H 'accept: application/json, */*;q=0.5' -d '{"circuit_json":{"cols":[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]},"step":0}'
```
<img width="770" alt="Screenshot 2024-11-05 at 16 19 53" src="https://github.com/user-attachments/assets/0a0edb0a-c090-4cd6-abad-347346cb8c26">


もしご対応が難しい場合は、全て空のステップの場合はリクエストを投げないようにするなどで回避しようと思いますのでご相談いただければと思います。

**Comment by yasuhito** [comment]
ありがとうございます! こちら修正します。

**Comment by yasuhito** [comment]
@AkiyukiOkayasu こちらもいったん閉じて OK でしょうか?

**Comment by AkiyukiOkayasu** [comment]
@yasuhito はい、大丈夫です
