### ISSUE TITLE
コントロール可能なゲートの種類?

### ISSUE THREAD

**Issue by yasuhito** [yasuhito/qni-viewer#61]
@AkiyukiOkayasu コントロール可能なゲートの種類は、どれにしましょう?

現在は X, Phase, ● がそれぞれコントロールゲートとくっつくようになっています。
それ以外に、もし H などもコントロールゲートとくっつける必要がありましたら、対応しますのでお知らせください。

すべてのゲート
- H
- X (CNOT)
- Y
- Z
- Phase (CPhase)
- RX
- RY
- RZ
- ● (CZ)

**Comment by AkiyukiOkayasu** [comment]
了解しました！

@TakahanaK 本件いかがですか？

**Comment by TakahanaK** [comment]
確認します！

**Comment by yasuhito** [comment]
みなさまありがとうございました。
Slack で確認がとれました。

必要なゲート:
- H, X, Y, Z, Rx, Ry, Rz, Measure
- CX, CPhase、CZ (C だけつなげたもの)
- QFT, Oracle

**Comment by AkiyukiOkayasu** [comment]
@yasuhito CX, CPhase, CZについての僕が認識が合っているか、念のため確認させてください。
このスクショの左からCX, CPhase, CZという認識なのですが、間違いないですか？
<img width="552" alt="Screenshot 2024-11-05 at 15 41 37" src="https://github.com/user-attachments/assets/1f6fd2b5-0b1c-43fb-8e1a-d020fb79f8f8">

参考までに表示用cURLコマンドです。
```shell
curl -X GET http://localhost:3000/ -H 'accept: application/json' -H 'content-type: application/json' -H 'content-type: application/json' -H 'accept: application/json, */*;q=0.5' -d '{"circuit_json":{"cols":[["•","X",1],["•","P(0.0)",1],["•","Z",1]]},"step":0}'
```

**Comment by yasuhito** [comment]
@AkiyukiOkayasu はい、そちらすべてあっております。
CZ については、コントロールゲートと Z をつなげたものと、コントロールゲートだけをつなげたものも (向きに関係なく) すべてまったく同じように動きます。これらまとめて CZ と書きます。

ぜんぶ同じ!
![CleanShot 2024-11-12 at 11 25 42](https://github.com/user-attachments/assets/b2045ad4-56fc-4a75-a533-3c9cf05b3be0)

**Comment by AkiyukiOkayasu** [comment]
ありがとうございます！そもそも僕の量子コンピューターの理解が怪しいことに問題がありますね...。今後ももし僕の用語の使い方などおかしいところあればご指摘いただけると非常に助かります。
