### ISSUE TITLE
ステップ0の位置について

### ISSUE THREAD

**Issue by AkiyukiOkayasu** [yasuhito/qni-viewer#65]
現状のでstep0を指定するとこのような位置になると思いますが、
<img width="779" alt="Screenshot 2024-11-05 at 16 54 20" src="https://github.com/user-attachments/assets/97ac7a85-ce71-497b-8c4c-aba364541b52">

隠れた初期値の直後にステップを設定できるようにしたいそうです。こういうイメージです。
![462541728_1561170074507430_7594050299988981625_n](https://github.com/user-attachments/assets/9e0c49dd-d88e-4fc7-8b49-b8f6fdf0ed5f)

これを高宮さん側でご対応いただくのはかなり面倒そうな予感がするので、 https://github.com/yasuhito/qni-viewer/pull/54 の変更を取り消していただいて、私が送信するJSONの最初と最後に["|0>","|0>","|0>"]と["Measure","Measure","Measure"]を毎回つけるようにするのはいかがでしょうか？

**Comment by AkiyukiOkayasu** [comment]
そういえば、JSON側に毎回["|0>","|0>","|0>"]と["Measure","Measure","Measure"]をつけるようにすれば、こちら https://github.com/yasuhito/qni-viewer/issues/55#issuecomment-2456437083 の空JSONのエラーも起こりえなくなりますね。

**Comment by TakahanaK** [comment]
@AkiyukiOkayasu 上記提案の場合、初期値ゲートと測定ゲート抜いて15step分を空のstep(ゲートが置ける)として担保可能なんでしたっけ？

**Comment by AkiyukiOkayasu** [comment]
@TakahanaK 空JSONのエラーの件ですよね。経緯をまとめます。

## 空ステップの表示
空ステップは3点リーダーが表示されるように変更していただいてます。

<img width="269" alt="Screenshot 2024-11-05 at 21 35 28" src="https://github.com/user-attachments/assets/e97ef208-f315-4d2e-b185-b1344ddd3582">

以下のような空配列"[]"の入力で空ステップが表示されます。
```json
{
	"circuit_json": {
		"cols": [
			["X",1,1],
			[] ←空ステップが表示される
		]
	},
	"step": 1
}
```

## 15ステップ全てを空ステップに

現在の初期値000と最後の測定がQni-Viewer内部で固定されており、JSONにも含まない仕様ですと、15ステップ全て空のJSONは当然こうなります。

```json
{
	"circuit_json": {
		"cols": [
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
		]
	},
	"step": 0
}
```

Qni-Viewerは要素全てが空配列のJSONは想定していないためか、パースする際にエラーになります。その報告がこちら https://github.com/yasuhito/qni-viewer/issues/55#issuecomment-2456437083 でした。

## 仮に元の仕様に戻す場合

初期値000と最後の測定も毎回JSONに含んだ以下のようなものを送信します。初期値と測定がJSONに含まれることでエラーを引き起こす入力が発生しないはず、というのが提案です。

```json
{
	"circuit_json": {
		"cols": [
			["|0>","|0>","|0>"],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			["Measure", "Measure", "Measure"]
		]
	},
	"step": 0
}
```

実際、現状のQni-ViewerでもJSON要素が全て空配列でなければ（空ステップが大量に連続しても）、問題なく描画してくれます。

<img width="787" alt="Screenshot 2024-11-05 at 21 47 33" src="https://github.com/user-attachments/assets/69bc7163-9b34-434a-8da0-cfcb15007785">

**Comment by TakahanaK** [comment]
@AkiyukiOkayasu 
最終的に、以下の部分が15stepになれば良いです。
<img width="755" alt="スクリーンショット 2024-11-06 10 31 15" src="https://github.com/user-attachments/assets/a88de7b3-dabf-4781-b53c-3101c66674bf">

**Comment by AkiyukiOkayasu** [comment]
はい、その認識は大丈夫です

**Comment by yasuhito** [comment]
@AkiyukiOkayasu  クライアント側で最初と最後に["|0>","|0>","|0>"]と["Measure","Measure","Measure"]を毎回つける、でもおっしゃるように修正は可能ですが、ステップのインデクス番号がいっこずれてしまうので、逆にバグりやすいかなと思いました。Qni 側でそのへんの汚い処理はやってしまって、クライアント側からは理想的な JSON しか送らない/受け取らない、という風にしようと思いますが、いかがでしょうか。

**Comment by AkiyukiOkayasu** [comment]
@yasuhito そうですね、おっしゃる通りQni側でご対応いただいた方が間違いないと私も思います。
なるべくお手間かけないように思ったのですが、かえって気をつかわせてしまったようで恐縮です。ご提案の方針で実装いただければと思います。

**Comment by yasuhito** [comment]
@AkiyukiOkayasu #68 で PR を出しましたので、お時間あるときにご確認おねがいします!

**Comment by yasuhito** [comment]
#68 をマージしましたのでこちら閉じます。
