### ISSUE TITLE
縦線表示について

### ISSUE THREAD

**Issue by AkiyukiOkayasu** [yasuhito/qni-viewer#66]
縦線についての状況を整理させてください。

## 縦線が表示される場合

Qniの挙動に則る。以下の縦線表示は全て正しい。

<img width="565" alt="Screenshot 2024-11-05 at 17 41 35" src="https://github.com/user-attachments/assets/4082ac36-7a8b-4e08-81bd-e791dfe89260">

[再現用Qniリンク](https://qniapp.net/%7B%22cols%22%3A%5B%5B%22%E2%80%A2%22%2C%22%E2%80%A2%22%5D%2C%5B%22%E2%80%A2%22%2C%22H%22%5D%2C%5B%22%E2%80%A2%22%2C%22P(%CF%80_2)%22%5D%2C%5B%22%E2%80%A2%22%2C%22Rx(%CF%80_2)%22%5D%2C%5B%22%E2%80%A2%22%2C%22Ry(%CF%80_2)%22%5D%2C%5B%22%E2%80%A2%22%2C%22Rz(%CF%80_2)%22%5D%2C%5B%22%E2%80%A2%22%2C%22X%22%5D%2C%5B%22%E2%80%A2%22%2C%22Y%22%5D%2C%5B%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22Swap%22%2C%22Swap%22%5D%2C%5B%22%E2%80%A2%22%2C%22Swap%22%5D%5D%7D)

### QFTとOracle

QFTとOracleは3qubit固定なので、同じステップに複数ブロックが配置されることは物理的に有り得ない。
したがってQFT, Oracleが配置されたステップに縦線が表示されることはない。

## 縦線表示のデータ取得

@yasuhito こちらお打ち合わせからふわっとしたままなので方針を決めさせてください。

縦線表示は演出でも使用されるため、Qni-Viewerで縦線が表示されたことをHTTPリクエストの戻り値などで取得したいです。現状のHTTPリクエストの戻り値"state_vector", "measured_bits"に加えて以下の要素を加えていただくのは如何でしょうか？

```json
    "vertical_lines": [
        {
            "step": 3, 
            "begin": 0,
            "length": 2
        },
        {
            "step": 4, 
            "begin": 1,
            "length": 1
        }
    ]
```
step: どのステップなのか 0-15
begin: 何qubit目から縦線が始まるのか 0 or 1
length: 縦線の長さ（何qubit分の長さか） 1 or 2

もし他にベターなやり方あればご提案いただけますと幸いです。

@takahanaK 全体的に齟齬がないか確認していただくために通知を飛ばしておきます

**Comment by yasuhito** [comment]
@AkiyukiOkayasu JSON フォーマットですが、以下はいかがでしょうか。

```json
{
  "vertical_lines": [
    {
      "step": 3,
      "endpoints": [0, 2]
    }
  ]
}
```

たとえば CNOT や CZ があったときに、どのビットが `begin` かは不明確なので、単純に線分の終点 2 つを返せばいいかなと思いました。

**Comment by AkiyukiOkayasu** [comment]
@yasuhito たしかにおっしゃる通りですね。ご提案のフォーマットで実装いただけますと幸いです。
